-- MySQL Script generated by MySQL Workbench
-- Fri Jul  8 01:16:56 2022
-- Model: Trackme    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Trackme
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Trackme
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Trackme` DEFAULT CHARACTER SET utf8 ;
USE `Trackme` ;

-- -----------------------------------------------------
-- Table `Trackme`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trackme`.`Usuario` (
    `UserID` INT NOT NULL,
    Contraseña VARCHAR(45) NOT NULL,
    Nombre VARCHAR(45) NOT NULL,
    Apellido VARCHAR(45) NOT NULL,
    Correo VARCHAR(45) NOT NULL,
    Ubicacion VARCHAR(100) NOT NULL,
    PRIMARY KEY (UserID)
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `Trackme`.`Dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trackme`.`Dispositivo` (
  `MAC-Adress` VARCHAR(12) NOT NULL,
  `User-ID` INT NULL,
  PRIMARY KEY (`MAC-Adress`),
  INDEX `UserIDForeanKey_idx` (`User-ID` ASC) VISIBLE,
  CONSTRAINT `UserIDForeanKey`
    FOREIGN KEY (`User-ID`)
    REFERENCES `Trackme`.`Usuario` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trackme`.`Gateway`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trackme`.`Gateway` (
  `ID-Gateway` INT NOT NULL AUTO_INCREMENT,
  `Token` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`ID-Gateway`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trackme`.`Torre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trackme`.`Torre` (
  `IDTorre` INT NOT NULL,
  `Ubicacion` VARCHAR(100) NOT NULL,
  `ID-Gateway` INT NOT NULL,
  PRIMARY KEY (`IDTorre`),
  INDEX `ID-GatewayForeankey_idx` (`ID-Gateway` ASC) VISIBLE,
  CONSTRAINT `ID-GatewayForeankey`
    FOREIGN KEY (`ID-Gateway`)
    REFERENCES `Trackme`.`Gateway` (`ID-Gateway`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trackme`.`Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trackme`.`Registro` (
  `IDTorre` INT NOT NULL,
  `MACDispositivo` VARCHAR(12) NOT NULL,
  `MACReferencio` VARCHAR(12) NOT NULL,
  `FechayHora` DATETIME NOT NULL,
  INDEX `MacDispositivoforeanKey_idx` (`MACDispositivo` ASC) VISIBLE,
  INDEX `IDTorreForeanKey_idx` (`IDTorre` ASC) VISIBLE,
  CONSTRAINT `MacDispositivoforeanKey`
    FOREIGN KEY (`MACDispositivo`)
    REFERENCES `Trackme`.`Dispositivo` (`MAC-Adress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDTorreForeanKey`
    FOREIGN KEY (`IDTorre`)
    REFERENCES `Trackme`.`Torre` (`IDTorre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
